"""Added new field to user user_status default value

Revision ID: 4be0eb6d045b
Revises: ece073ac2980
Create Date: 2025-04-21 23:20:26.991129

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '4be0eb6d045b'
down_revision: Union[str, None] = 'ece073ac2980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
